{
 "title": "WAGO SNMP Monitoring",
 "description": "Monitor CPU and trafic on WAGO PLC and Ethernet Switches",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": "SHOW TAG VALUES  FROM \"snmp\" WITH KEY = \"device\" "
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_device ($tag_agent_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "query": "SELECT mean(\"cpuload\") FROM \"snmp\" WHERE (\"device\" =~ /^$Device$/) AND $timeFilter GROUP BY time($__interval), \"device\", \"agent_host\" fill(previous)",
     "select": [
      [
       { "params": [ "cpuload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "cpuload" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$Device$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$tag_device: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT  8*non_negative_derivative(mean(\"ifInOctets\"),1s) as \"in\",  8*non_negative_derivative(mean(\"ifOutOctets\"),1s) as \"out\" FROM \"interface\" WHERE $timeFilter and (\"device\" =~ /^$Device$/) GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "description" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "cpuload" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "Device" },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT  8*non_negative_derivative(mean(\"ifInOctets\"),1m) as \"in\",  8*non_negative_derivative(mean(\"ifOutOctets\"),1m) as \"out\" FROM \"interface\" WHERE $timeFilter and (\"device\" =~ /^$Device$/) GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT  non_negative_derivative(mean(\"ifInUcastPkts\"),1m) as \"in\",  non_negative_derivative(mean(\"ifOutUcastPkts\"),1m) as \"out\" FROM \"interface\" WHERE $timeFilter and (\"device\" =~ /^$Device$/) GROUP BY time($__interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT  8*non_negative_derivative(mean(\"ifInOctets\"),1m) as \"in\",  8*non_negative_derivative(mean(\"ifOutOctets\"),1m) as \"out\" FROM \"interface\" WHERE $timeFilter and (\"device\" =~ /^$Device$/) GROUP BY time(1m), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth share (in)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifDescr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT  8*non_negative_derivative(mean(\"ifInOctets\"),1m) as \"in\" FROM \"interface\" WHERE (\"ifDescr\" != 'br0') AND(\"ifDescr\" != 'lo') AND (\"ifDescr\" != 'eth0') AND $timeFilter and (\"device\" =~ /^$Device$/) GROUP BY time(1m), \"ifDescr\" fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Bandwidth share (out)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ifDescr",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "interface",
     "query": "SELECT  8*non_negative_derivative(mean(\"ifInOctets\"),1m) as \"out\" FROM \"interface\" WHERE (\"ifDescr\" != 'br0') AND(\"ifDescr\" != 'lo') AND (\"ifDescr\" != 'eth0') AND $timeFilter and (\"device\" =~ /^$Device$/) GROUP BY time(1m), \"ifDescr\" fill(null)",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  }
 ]
}